include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Error rules
    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    no_logic_in_create_state: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    sized_box_for_whitespace: true
    use_full_hex_values_for_flutter_colors: true
    use_key_in_widget_constructors: true
    
    # Style rules
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    annotate_overrides: true
    avoid_init_to_null: true
    avoid_return_types_on_setters: true
    await_only_futures: true
    camel_case_types: true
    empty_constructor_bodies: true
    prefer_final_fields: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    
analyzer:
  errors:
    todo: ignore
    missing_required_param: error
    missing_return: error
